nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.3.1.cjs
pnpMode: strict
enableGlobalCache: false # 호스트의 캐시를 참조 하지 못하게 false 한다. 일관성 있는 설치 보장
supportedArchitectures: # pnp 사용 시 프로젝트와 Docker실행환경을 맞추기 위해 필수
  os: [darwin, linux] # Mac OS & Linux 작동
  cpu: [arm64] # M1/M2 최적화 패키지 사용 지정
packageExtensions:
  'winston@*':
    dependencies:
      'logform': '^2.6.1'
