version: '3.8'

services:
  oauth:
    build:
      context: .
      target: production
    image: smpark9596/oauth2.0:${VERSION}
    container_name: oauth2.0_${VERSION}
    ports:
      - '3333:5555'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    volumes:
      - smpark_log:/usr/src/oauth_log
    command: yarn prod

networks:
  default:
    name: smpark_oauth_network_prod

volumes:
  smpark_log:
