name: Deploy to MacBook

on:
  push:
    branches: [main]

env:
  DOCKER_USERNAME: smpark9596
  DOCKER_REPOSITORY: oauth2.0
  DOCKER_IMAGE: smpark9596/oauth2.0
  VERSION: 1.0.0
  APP_PORT: 5555
  NGINX_PORT: 3333

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }} .
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}

      - name: Deploy application
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
          docker stop oauth2.0_${{ env.VERSION }} || true
          docker rm oauth2.0_${{ env.VERSION }} || true
          docker network create smpark_oauth_network_prod || true
          docker run -d --name oauth2.0_${{ env.VERSION }} \
            -p ${{ env.NGINX_PORT }}:${{ env.APP_PORT }} \
            -e NODE_ENV=production \
            --env-file .env.production \
            -v smpark_log:/usr/src/oauth2.0/src/log \
            --network smpark_oauth_network_prod \
            ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }} \
            yarn prod

      - name: Update Nginx configuration
        run: |
          sudo tee /opt/homebrew/etc/nginx/nginx.conf > /dev/null <<EOT
          user smpark admin;
          worker_processes auto;
          events {
              worker_connections 1024;
          }
          http {
              include       mime.types;
              default_type  application/octet-stream;
              sendfile        on;
              keepalive_timeout  65;
              server {
                  listen 80;
                  server_name smpark.ddns.net;
                  return 301 https://\$server_name\$request_uri;
              }
              server {
                  listen 443 ssl;
                  server_name smpark.ddns.net;
                  ssl_certificate /etc/letsencrypt/live/smpark.ddns.net/fullchain.pem;
                  ssl_certificate_key /etc/letsencrypt/live/smpark.ddns.net/privkey.pem;
                  ssl_protocols TLSv1.2 TLSv1.3;
                  location / {
                      proxy_pass http://localhost:${{ env.NGINX_PORT }};
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade \$http_upgrade;
                      proxy_set_header Connection 'upgrade';
                      proxy_set_header Host \$host;
                      proxy_cache_bypass \$http_upgrade;
                  }
              }
          }
          EOT

      - name: Restart Nginx
        run: sudo brew services restart nginx
